steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/csjp-gcloud/subcalc'
  - '.'

- name: 'gcr.io/csjp-gcloud/subcalc'
  id: Run build
  entrypoint: /ci/build.sh

- name: 'gcr.io/csjp-gcloud/subcalc'
  id: Lint build
  entrypoint: /ci/lint.sh

- name: 'gcr.io/csjp-gcloud/subcalc'
  id: Test build
  entrypoint: /ci/test.sh
