# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["csjayp@gmail.com"]
description = "HTTP API for the subcalc codebase"
language = "go"
manifest_version = 3
name = "subcalc-api"
service_id = ""

[local_server]

[scripts]
  build = "go build -o bin/main.wasm ."
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"
